### ISSUE TITLE
Conflicts with native URL API

### ISSUE THREAD

**Issue by ryanseddon** [lloyd/urlparse.js#1]
FF4 looks like it has URL native object on the window host object for their support of create/revokeObjectURL(). I'd be wary of namespace conflicts.

**Comment by lloyd** [comment]
good point.  Perhaps the library should just expose a single function and attach it to window.URLParse()...

**Comment by lloyd** [comment]
(wish we had something like commonjs packaging in browsers :/)

**Comment by lloyd** [comment]
rather than populating window.URL with an object, expose a single parsing function at window.URLParse.  closed by 45896f68fbdd42955b3257cab4b5180ec4585cbf
